version: "3.9"
services:
  data:
    image: ccm_slam
    command: /bin/bash -c "python3 main.py ${AGENT_NUM} ${CATKIN_WS}/dataset"
    network_mode: "host"
    working_dir: ${CATKIN_WS}/code/player
    volumes:
      - ${CODE}:${CATKIN_WS}/code
      - "${DATASET}${AGENT_NUM}:${CATKIN_WS}/dataset"
    environment:
      ROS_MASTER_URI: ${ROS_MASTER_URI}
      AGENT_NUM: ${AGENT_NUM}
      
